spring.application.name=casier-api
spring.main.allow-circular-references=true
logging.file.name=/opt/microservices/logs/casierapi.log
//logging.file.name=/home/si/casier/logs/casierapi.log
#spring.jpa.properties.hibernate.format_sql=true
