#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.application.name=fnc
#logging.file.name=/opt/microservices/logs/casierfnc.log
logging.file.name=/home/lawson/Téléchargements/casier-master/config/fnc.properties
logging.level.org.springframework.web=DEBUG