<<<<<<< HEAD
spring.application.name=gateway
logging.file.name=/opt/microservices/logs/casiergateway.log

=======
spring.application.name=gatewaypublic
logging.file.name=/opt/microservices/logs/gatewaypublic.log
>>>>>>> f7f6fa116f12fce026fa4a0a33b75bf3fa50f193
