server.port=8282

spring.datasource.url= jdbc:postgresql://192.168.93.85:5432/db_casier
#spring.datasource.url= jdbc:postgresql://localhost:5432/db_casier
spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.password=AdminJlM#123456
#spring.datasource.url= jdbc:postgresql://192.168.93.85:5432/db_casier

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.hibernate.ddl-auto=update
eureka.instance.hostname=localhost
projectName=Demande de duplicatat de nationalité, suivi des demandes
server.tomcat.max-swallow-size=-1
spring.servlet.multipart.max-file-size=500000KB
spring.servlet.multipart.max-request-size=500000KB
chemin.base.fichiers=/opt/DGDNData
fichier.serveur.url=http://160.242.199.218:8282/pieces
#poste.apiUrl=https://api.trak.codes
#poste.endPoint=https://api.trak.codes
#poste.api.key=RMBvSWFZb5U2FCCaphFoUZCYmil9iZihTjMzKB8yUOpYl1euQjkfj2jcEdONbjNU
#poste.external.create.case=https://api.trak.codes/v0/rpc/externalcreatecase
poste.apiUrl=https://api.trak.codes
poste.endPoint=https://api.trak.codes
poste.api.key=1jakjNphKO6DUiPK2gsTQilQA9XgRgwLpkZDwUUEDhJzylcUC3OmkraUZIVirl6I
poste.external.create.case=https://api.trak.codes/v0/rpc/externalcreatecase

email_base_url=http://192.168.93.96:8282
user.service.url=http://192.168.93.96:8081/
ftp.api.base_url=http://localhost:8484/
report.folder=/opt/microservices/reports
duplicata.frais.copie=100
recette.notification.url=http://192.168.93.75:8080/paiement-serach-api/

b3.vierge=D:/casier/sncj/reports/modeles/bulletin_b3_vierge.jrxml
b3Morale.vierge=D:/casier/sncj/reports/modeles/bulletin_B3_MORALE_vierge.jrxml
b3Morale.avecCondamnations=D:/casier/sncj/reports/modeles/bulletin_B3_MORALE.jrxml
b3.avecCondamnations=D:/casier/sncj/reports/modeles/bulletin_b3.jrxml
cje.vierge=

b1.vierge=D:/casier/sncj/reports/modeles/bulletin_b1_vierge.jrxml
b2.vierge=D:/casier/sncj/reports/modeles/bulletin_b2_vierge.jrxml
b2.avecCondamnations==D:/casier/sncj/reports/modeles/bulletin_b2.jrxml
b1Morale.vierge=D:/casier/sncj/reports/modeles/bulletin_B1_MORALE_vierge.jrxml
b1Morale.avecCondamnations=D:/casier/sncj/reports/modeles/bulletin_B1_MORALE.jrxml
b1.avecCondamnations=D:/casier/sncj/reports/modeles/bulletin_b1.jrxml
tg.armoirie=D:/casier/sncj/reports/modeles/images/armoirie_togo.jpg
tg.signature=D:/casier/sncj/reports/modeles/images/signature.png
tg.neant=D:/casier/sncj/reports/modeles/images/neant.jpg
tg.background=D:/casier/sncj/reports/modeles/images/bg.png
file.server.path=http://localhost:8880/pieces/

fnc.base.url=http://localhost:8383/
stat.template.base=D://JAVA_HOME/SPRING BOOT/casier/reports/modeles

#API ATD
base_url=https://xjustice.sandbox.gouv.tg/
#base_url=https://justice.xflow.gouv.tg/
x-flow.api.email=mjlapi@xflow.gouv.tg
x-flow.api.password=7PjygW3s7pT7$C#7ewxaGyQ7jVS%
#x-flow.api.email=mjluser@xflow.tg
#x-flow.api.password=mJL1Us6rFlow+#
support.mail.adress=mjl.support@justice.gouv.tg

print.api.url=http://localhost:8081/print