#port


server.port=8181

#Pour le service utilisateurs
spring.cloud.gateway.routes[0].id=casier-service
spring.cloud.gateway.routes[0].uri=http://localhost:8282/
spring.cloud.gateway.routes[0].predicates[0]=Path=/permissions/** 

spring.cloud.gateway.routes[1].id=casier-service
spring.cloud.gateway.routes[1].uri=http://localhost:8282/
spring.cloud.gateway.routes[1].predicates[0]=Path=/utilisateurs/**

spring.cloud.gateway.routes[2].id=casier-service
spring.cloud.gateway.routes[2].uri=http://localhost:8282/
spring.cloud.gateway.routes[2].predicates[0]=Path=/references/**

spring.cloud.gateway.routes[3].id=casier-service
spring.cloud.gateway.routes[3].uri=http://localhost:8282/
spring.cloud.gateway.routes[3].predicates[0]=Path=/demandes/**

spring.cloud.gateway.routes[4].id=cato-service
spring.cloud.gateway.routes[4].uri=http://localhost:8282/
spring.cloud.gateway.routes[4].predicates[0]=Path=/paiements/**


spring.cloud.gateway.routes[5].id=casier-service
spring.cloud.gateway.routes[5].uri=http://localhost:8282/
spring.cloud.gateway.routes[5].predicates[0]=Path=/permission-categories/**

spring.cloud.gateway.routes[6].id=casier-service
spring.cloud.gateway.routes[6].uri=http://localhost:8282/
spring.cloud.gateway.routes[6].predicates[0]=Path=/roles/**


spring.cloud.gateway.routes[7].id=casier-service
spring.cloud.gateway.routes[7].uri=http://localhost:8282/
spring.cloud.gateway.routes[7].predicates[0]=Path=/role-permissions/**


spring.cloud.gateway.routes[8].id=casier-service
spring.cloud.gateway.routes[8].uri=http://localhost:8282/
spring.cloud.gateway.routes[8].predicates[0]=Path=/service-demandeur-b2s/**


spring.cloud.gateway.routes[9].id=casier-service
spring.cloud.gateway.routes[9].uri=http://localhost:8282/
spring.cloud.gateway.routes[9].predicates[0]=Path=/point-retraits/**


spring.cloud.gateway.routes[10].id=casier-service
spring.cloud.gateway.routes[10].uri=http://localhost:8282/
spring.cloud.gateway.routes[10].predicates[0]=Path=/fonctions/**


spring.cloud.gateway.routes[11].id=casier-service
spring.cloud.gateway.routes[11].uri=http://localhost:8282/
spring.cloud.gateway.routes[11].predicates[0]=Path=/utilisateur-casiers/**

spring.cloud.gateway.routes[12].id=casier-service
spring.cloud.gateway.routes[12].uri=http://localhost:8282/
spring.cloud.gateway.routes[12].predicates[0]=Path=/userCasier-pointRetraits/**

spring.cloud.gateway.routes[13].id=casier-service
spring.cloud.gateway.routes[13].uri=http://localhost:8282/
spring.cloud.gateway.routes[13].predicates[0]=Path=/type-demandes/**

spring.cloud.gateway.routes[14].id=casier-service
spring.cloud.gateway.routes[14].uri=http://localhost:8282/
spring.cloud.gateway.routes[14].predicates[0]=Path=/paiement-actives/**

spring.cloud.gateway.routes[15].id=casier-service
spring.cloud.gateway.routes[15].uri=http://localhost:8282/
spring.cloud.gateway.routes[15].predicates[0]=Path=/entite-demandeur-b2s/**


spring.cloud.gateway.routes[16].id=casier-service
spring.cloud.gateway.routes[16].uri=http://localhost:8282/
spring.cloud.gateway.routes[16].predicates[0]=Path=/pays/**

spring.cloud.gateway.routes[17].id=casier-service
spring.cloud.gateway.routes[17].uri=http://localhost:8282/
spring.cloud.gateway.routes[17].predicates[0]=Path=/categorie-demandeurs/**

spring.cloud.gateway.routes[18].id=casier-service
spring.cloud.gateway.routes[18].uri=http://localhost:8282/
spring.cloud.gateway.routes[18].predicates[0]=Path=/categories-socio-professionnelles/**

spring.cloud.gateway.routes[19].id=casier-service
spring.cloud.gateway.routes[19].uri=http://localhost:8282/
spring.cloud.gateway.routes[19].predicates[0]=Path=/professions/**

spring.cloud.gateway.routes[20].id=casier-service
spring.cloud.gateway.routes[20].uri=http://localhost:8282/
spring.cloud.gateway.routes[20].predicates[0]=Path=/localites/**

spring.cloud.gateway.routes[21].id=casier-service
spring.cloud.gateway.routes[21].uri=http://localhost:8282/
spring.cloud.gateway.routes[21].predicates[0]=Path=/cours-d-appels/**


spring.cloud.gateway.routes[22].id=casier-service
spring.cloud.gateway.routes[22].uri=http://localhost:8282/
spring.cloud.gateway.routes[22].predicates[0]=Path=/variables/**


spring.cloud.gateway.routes[23].id=casier-service
spring.cloud.gateway.routes[23].uri=http://localhost:8282/
spring.cloud.gateway.routes[23].predicates[0]=Path=/model-sms/**

spring.cloud.gateway.routes[24].id=casier-service
spring.cloud.gateway.routes[24].uri=http://localhost:8282/
spring.cloud.gateway.routes[24].predicates[0]=Path=/situation-matrimoniales/**

spring.cloud.gateway.routes[25].id=casier-service
spring.cloud.gateway.routes[25].uri=http://localhost:8282/
spring.cloud.gateway.routes[25].predicates[0]=Path=/sexes/**

spring.cloud.gateway.routes[26].id=casier-service
spring.cloud.gateway.routes[26].uri=http://localhost:8282/
spring.cloud.gateway.routes[26].predicates[0]=Path=/logs/**

spring.cloud.gateway.routes[27].id=casier-service
spring.cloud.gateway.routes[27].uri=http://localhost:8282/
spring.cloud.gateway.routes[27].predicates[0]=Path=/prefectures/**













